version: "3.8"
services:
  ui:
    build:
      context: .
      dockerfile: ./docker-compose/Dockerfile.ui
      target: ui
    image: quay.io/cloudminds/dagger-ui:latest
    hostname: dagger-ui
    container_name: dagger-ui
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - dagger
  backend:
    build:
      context: .
      dockerfile: ./docker-compose/Dockerfile.backend
      target: backend
    image: quay.io/cloudminds/dagger-backend:latest
    hostname: dagger-backend
    container_name: dagger-backend
    environment:
      - LOKI_SERVER=http://172.16.31.102:3100 # your loki server address (optional)
    ports:
      - "8000:8000"
    command: ["sh", "-c", "./dagger"]
    networks:
      - dagger
    volumes:
      - "static_data:/usr/src/app/static:rw"
      - "sqlite_data:/usr/src/app/db:rw"
      - "dagger_conf:/etc/dagger/:rw"

volumes:
  sqlite_data:
    driver: local
  static_data:
    driver: local
  dagger_conf:
    driver: local

networks:
  dagger:
    driver: bridge
