version: "3.8"
services:
  ui:
    image: quay.io/cloudminds/dagger-ui:latest
    hostname: dagger-ui
    container_name: dagger-ui
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - dagger
  backend:
    image: quay.io/cloudminds/dagger-backend:latest
    hostname: dagger-backend
    container_name: dagger-backend
    environment:
      - LOKI_SERVER=http://127.0.0.1:3100 # your loki server address (optional)
    ports:
      - "8000:8000"
    command: ["sh", "-c", "./dagger"]
    networks:
      - dagger
    volumes:
      - "./config/dagger.ini:/etc/dagger/dagger.ini"
      - "static_data:/usr/src/app/static:rw"
      - "sqlite_data:/usr/src/app/db:rw"

volumes:
  sqlite_data:
    driver: local
  static_data:
    driver: local

networks:
  dagger:
    driver: bridge
