apiVersion: v1
data:
  dagger.ini: |
    [users]
    ; allow register
    allow_sign_up = false
    admin_username = admin
    admin_passwod = admin
    
    [ldap]
    enabled = false
    ldap_host = ldap
    ldap_port = 389
    ldap_base_dn =
    ldap_bind_username =
    ldap_bind_password =
    ldap_username_key = uid
    ldap_mail_key = mail
kind: ConfigMap
metadata:
  name: dagger-conf

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dagger-service
    dagger.backend: sqlite
  name: sqlite-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dagger-service
    dagger.backend: static
  name: static-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dagger-backend
  name: dagger-backend
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: dagger-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dagger-ui
  name: dagger-ui
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: dagger-ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dagger-backend
  name: dagger-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagger-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dagger-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./dagger
          image: quay.io/cloudminds/dagger-backend:latest
          name: dagger-backend
          env:
            - name: LOKI_SERVER
              # your loki service endpoint
              value: http://<LOKI_ENDPOINT>:3100
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumkeMounts:
            - mountPath: /usr/src/app/static
              name: static-data
            - mountPath: /usr/src/app/db
              name: sqlite-data
            - mountPath: /etc/dagger
              name: dagger-conf
      restartPolicy: Always
      volumes:
        - name: static-data
          persistentVolumeClaim:
            claimName: static-data
        - name: sqlite-data
          persistentVolumeClaim:
            claimName: sqlite-data
        - name: dagger-conf
          configMap:
            defaultMode: 420
            name: dagger-conf

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dagger-ui
  name: dagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagger-ui
  template:
    metadata:
      labels:
        app: dagger-ui
    spec:
      containers:
        - image: quay.io/cloudminds/dagger-ui:latest
          name: dagger-ui
          ports:
            - containerPort: 8080
      restartPolicy: Always
