name: dagger ci

on:
  push:
    branches:
      - "main"
    tags:
      - "**"
    paths-ignore: ["**/*.md"]
  pull_request:
    paths-ignore: ["**/*.md"]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data

      - name: Prepare
        id: prep
        run: |
          VERSION=noop
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=edge
            fi
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="$TAGS,${MINOR},${MAJOR},latest"
          elif [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,sha-${GITHUB_SHA::8}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Login to Quay.io
        uses: docker/login-action@v1.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUARIO_USERNAME }}
          password: ${{ secrets.QUARIO_PASSWORD }}

      - name: Build backend and push
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose/Dockerfile.backend
          platforms: linux/amd64,linux/arm64,linux/386
          push: ${{ github.event_name != 'pull_request' }}
          tags: quay.io/cloudminds/dagger-backend:${{ steps.prep.outputs.tags }}

      - name: Build ui and push
        id: docker_build_ui
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose/Dockerfile.ui
          platforms: linux/amd64,linux/arm64,linux/386
          push: ${{ github.event_name != 'pull_request' }}
          tags: quay.io/cloudminds/dagger-ui:${{ steps.prep.outputs.tags }}
