name: dagger ci

on:
  push:
    branches: [main]
    paths-ignore: ["**/*.md"]
  pull_request:
    branches: [main]
    paths-ignore: ["**/*.md"]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.2
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.QUARIO_USERNAME }}
          password: ${{ secrets.QUARIO_PASSWORD }}

      - name: Build backend and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose/Dockerfile.backend
          push: true
          tags: quay.io/cloudminds/dagger-backend:latest

      - name: Build ui and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose/Dockerfile.ui
          push: true
          tags: quay.io/cloudminds/dagger-ui:latest
