name: dagger ci

on:
  push:
    paths-ignore: ["**/*.md"]
  pull_request:
    paths-ignore: ["**/*.md"]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Login to Quay.io
        uses: docker/build-push-action@v1.1.1
        with:
          registry: quay.io
          username: ${{ secrets.QUARIO_USERNAME }}
          password: ${{ secrets.QUARIO_PASSWORD }}

      - name: Build backend and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose/Dockerfile.backend
          push: true
          tags: quay.io/cloudminds/dagger-backend:${{ github.ref }}

      - name: Build ui and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose/Dockerfile.ui
          push: true
          tags: quay.io/cloudminds/dagger-ui:${{ github.ref }}
